Models/CarDTO.cs
namespace CarSaleProject.Models
{
    public class CarDTO
    {
        public decimal Price { get; set; }
        public DateTime ListingDate { get; set; }
        public int ListingNumber { get; set; }
        public string Brand { get; set; }
        public string Series { get; set; }
        public string Model { get; set; }
        public int Kilometers { get; set; }
        public IFormFile? File { get; set; }
        public string? FilePath { get; set; }
        public int CategoryId { get; set; }
        public List<CategoryDTO>? Categories { get; set; }



    }
}

Models/CategoryDTO.cs
namespace CarSaleProject.Models
{
    public class CategoryDTO
    {
        public string Name { get; set; }
        public int ListingNumber { get; set; }

        public IFormFile? File { get; set; }
        public string? FilePath { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace CarSaleProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CarSaleController.cs
using CarSaleProject.Models;
using CarSaleProject.Repositories;
using CategorySaleProject.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CarSaleProject.Controllers
{
    public class CarSaleController : Controller
    {
        private readonly ICarRepository _carRepository;
        private readonly ICategoryRepository _categoryRepository;

        public CarSaleController(ICarRepository carRepository, ICategoryRepository categoryRepository)
        {
            _carRepository = carRepository;
            _categoryRepository = categoryRepository;
        }

        [HttpGet]
        public IActionResult AddCar()
        {
            List<CategoryDTO> categories = _categoryRepository.GetAllCategories();
            CarDTO car = new CarDTO();
            car.Categories = categories;

            return View(car);
        }

        [HttpPost]
        public IActionResult AddCar(CarDTO car)
        {

            if (ModelState.IsValid)
            {

                if (car.File != null && car.File.Length > 0)
                {
                    DirectoryInfo fileType = new DirectoryInfo(car.File.FileName);
                    string fileName = Guid.NewGuid().ToString()+ fileType.Extension;

                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", fileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        car.File.CopyToAsync(stream);
                    }
                    car.FilePath = "/img/" + fileName;
                }
                else
                {
                    ViewBag.Message = "Lütfen bir dosya seçin.";
                }

                _carRepository.AddCar(car);
                return RedirectToAction("CarList");
            }
            return View(car);
        }

        public IActionResult CarList()
        {
            var cars = _carRepository.GetAllCars();
            return View(cars);
        }

        [HttpGet]
        public IActionResult UpdateCar(int listingNumber)
        {
            var car = _carRepository.GetCarByListingNumber(listingNumber);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        [HttpPost]
        public IActionResult UpdateCar(CarDTO car)
        {
            if (ModelState.IsValid)
            {
                _carRepository.UpdateCar(car);
                return RedirectToAction("CarList");
            }
            return View(car);
        }

        [HttpGet]
        public IActionResult DeleteCar(int listingNumber)
        {

            var car = _carRepository.GetCarByListingNumber(listingNumber);
            if (car == null)
            {
                return NotFound();
            }
            _carRepository.DeleteCar(car);  
            return RedirectToAction("CarList");           
        }
    }
}

Controllers/CategoryController.cs
using CarSaleProject.Models;
using CarSaleProject.Repositories;
using CategorySaleProject.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CategorySaleProject.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _carRepository;

        public CategoryController(ICategoryRepository categoryRepository)
        {
            _carRepository = categoryRepository;
        }

        [HttpGet]
        public IActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCategory(CategoryDTO category)
        {

            if (ModelState.IsValid)
            {

                if (category.File != null && category.File.Length > 0)
                {
                    DirectoryInfo fileType = new DirectoryInfo(category.File.FileName);
                    string fileName = Guid.NewGuid().ToString() + fileType.Extension;

                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", fileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        category.File.CopyToAsync(stream);
                    }
                    category.FilePath = "/img/" + fileName;
                }
                else
                {
                    ViewBag.Message = "Lütfen bir dosya seçin.";
                }

                _carRepository.AddCategory(category);
                return RedirectToAction("CategoryList");
            }

            return View(category);
        }

        public IActionResult CategoryList()
        {
            var cars = _carRepository.GetAllCategories();
            return View(cars);
        }

        [HttpGet]
        public IActionResult UpdateCategory(int listingNumber)
        {
            var category = _carRepository.GetCategoryByListingNumber(listingNumber);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        public IActionResult UpdateCategory(CategoryDTO category)
        {
            if (ModelState.IsValid)
            {
                _carRepository.UpdateCategory(category);
                return RedirectToAction("CategoryList");
            }
            return View(category);
        }

        [HttpGet]
        public IActionResult DeleteCategory(int listingNumber)
        {

            var category = _carRepository.GetCategoryByListingNumber(listingNumber);
            if (category == null)
            {
                return NotFound();
            }
            _carRepository.DeleteCategory(category);
            return RedirectToAction("CategoryList");
        }
    }
}

Controllers/HomeController.cs
using CarSaleProject.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CarSaleProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/CarSale/AddCar.cshtml
@model CarDTO

@{
    ViewData["Title"] = "Araba Ekle";

}

<h2 class="my-4">Araba Ekle</h2>

<form asp-action="AddCar" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label>Fiyat</label>
        <input type="number" class="form-control" asp-for="Price" />
    </div>
    <div class="form-group">
        <label>İlan Tarihi</label>
        <input type="date" class="form-control" asp-for="ListingDate" />
    </div>
    <div class="form-group">
        <label>İlan Numarası</label>
        <input type="number" class="form-control" asp-for="ListingNumber" />
    </div>
    <div class="form-group">
        <label>Marka</label>
        <input type="text" class="form-control" asp-for="Brand" />
    </div>
    <div class="form-group">
        <label>Seri</label>
        <input type="text" class="form-control" asp-for="Series" />
    </div>
    <div class="form-group">
        <label>Model</label>
        <input type="text" class="form-control" asp-for="Model" />
    </div>
    <div class="form-group">
        <label>KM</label>
        <input type="number" class="form-control" asp-for="Kilometers" />
    </div>
    <div class="form-group">
        <label>Kategori</label>
        @if(Model.Categories != null)
        {
            <select class="form-control" asp-for="CategoryId">
                <option value="">Seçiniz</option>
                @foreach (var category in Model.Categories)
                {
                    <option value="@category.ListingNumber">@category.Name</option>
                }
            </select>
        }
    </div>
    <div class="form-group">
        <label>Dosya Seç:</label>
        <input type="file" id="file" asp-for="File" />
    </div>
    <button type="submit" class="btn btn-primary">Ekle</button>
</form>

@if (ViewBag.Message != null)
{
    <p>@ViewBag.Message</p>
}

Views/CarSale/CarList.cshtml
@model IEnumerable<CarDTO>

@{
    ViewData["Title"] = "Araba Listesi";
}

<h2 class="my-4">Araba Listesi</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Fiyat</th>
            <th>İlan Tarihi</th>
            <th>İlan Numarası</th>
            <th>Marka</th>
            <th>Seri</th>
            <th>Model</th>
            <th>Resim</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var car in Model)
        {
            <tr>
                <td>@car.Price</td>
                <td>@car.ListingDate.ToShortDateString()</td>
                <td>@car.ListingNumber</td>
                <td>@car.Brand</td> 
                <td>@car.Series</td>
                <td>@car.Model</td>
                <td><img src="@car.FilePath" alt="Car Image" width="100" /></td>
                <td>
                    <a href="/CarSale/UpdateCar?listingNumber=@car.ListingNumber" class="btn btn-primary">Güncelle</a>
                    <a href="/CarSale/DeleteCar?listingNumber=@car.ListingNumber" class="btn btn-primary">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/CarSale/UpdateCar.cshtml
@model CarDTO

@{
    ViewData["Title"] = "Araba Güncelle";
}

<h2 class="my-4">Araba Güncelle</h2>

<form asp-action="UpdateCar" method="post">
    <div class="form-group">
        <label>Fiyat</label>
        <input type="number" class="form-control" asp-for="Price" />
    </div>
    <div class="form-group">
        <label>İlan Tarihi</label>
        <input type="date" class="form-control" asp-for="ListingDate" />
    </div>
    <div class="form-group">
        <label>İlan Numarası</label>
        <input type="number" class="form-control" asp-for="ListingNumber" />
    </div>
    <div class="form-group">
        <label>Marka</label>
        <input type="text" class="form-control" asp-for="Brand" />
    </div>
    <div class="form-group">
        <label>Seri</label>
        <input type="text" class="form-control" asp-for="Series" />
    </div>
    <div class="form-group">
        <label>Model</label>
        <input type="text" class="form-control" asp-for="Model" />
    </div>


    <button type="submit" class="btn btn-primary">Güncelle</button>
</form>

Views/Category/AddCategory.cshtml
@model CategoryDTO

@{
    ViewData["Title"] = "Kategori Ekle";
}

<h2 class="my-4">Kategori Ekle</h2>

<form asp-action="AddCategory" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label>Kategori Numarası</label>
        <input type="number" class="form-control" asp-for="ListingNumber" />
    </div>
    <div class="form-group">
        <label>Kategori Adı</label>
        <input type="text" class="form-control" asp-for="Name" />
    </div>

    <div class="form-group">
        <label>Dosya Seç:</label>
        <input type="file" id="file" asp-for="File" />
    </div>
    <button type="submit" class="btn btn-primary">Ekle</button>
</form>

@if (ViewBag.Message != null)
{
    <p>@ViewBag.Message</p>
}

Views/Category/CategoryList.cshtml
@model IEnumerable<CategoryDTO>

@{
    ViewData["Title"] = "Kategori Listesi";
}

<h2 class="my-4">Kategori Listesi</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Adı</th> 
            <th>Numara</th> 
            <th>Resim</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var category in Model)
        {
            <tr>
                <td>@category.Name</td>
                <td>@category.ListingNumber</td>
                <td><img src="@category.FilePath" alt="Car Image" width="100" /></td>
                <td>
                    <a href="/Category/UpdateCategory?listingNumber=@category.ListingNumber" class="btn btn-primary">Güncelle</a>
                    <a href="/Category/DeleteCategory?listingNumber=@category.ListingNumber" class="btn btn-primary">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Category/UpdateCategory.cshtml
@model CategoryDTO

@{
    ViewData["Title"] = "Kategori Güncelle";
}

<h2 class="my-4">Kategori Güncelle</h2>

<form asp-action="UpdateCategory" method="post">
    <div class="form-group">
        <label>Kategori Numarası</label>
        <input type="number" class="form-control" asp-for="ListingNumber" />
    </div>
    <div class="form-group">
        <label>Kategori Adı:</label>
        <input type="text" class="form-control" asp-for="Name" />
    </div>

    <button type="submit" class="btn btn-primary">Güncelle</button>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarSaleProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarSaleProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarSaleProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CarSale" asp-action="AddCar">Araba Ekle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CarSale" asp-action="CarList">Araba Listesi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="AddCategory">Kategori Ekle</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CarSaleProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>